; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
;default_envs = weact_mini_h750vbtx
default_envs = weact_mini_h743vitx

;[env:weact_mini_h750vbtx]
[env:weact_mini_h743vitx]
platform = ststm32
;board = weact_mini_h750vbtx
board = weact_mini_h743vitx
framework = arduino
lib_deps =
        bblanchon/ArduinoJson@^6.21.3
        pololu/VL53L0X@^1.3.1
        nrf24/RF24

; change microcontroller
;board_build.mcu = stm32h750vbt6
board_build.mcu = stm32h743vit6

; change MCU frequency
board_build.f_cpu = 480000000L

build_src_filter = +<Weact/*> -<ESP32/*>

; set upload and monitor speed
monitor_speed = 115200
monitor_port= /dev/ttyACM0
upload_speed = 115200
debug_tool = stlink
upload_protocol = stlink
;upload_protocol = dfu

build_type = debug

build_flags =
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-D USBCON
        -D ENABLE_USB_SER
        -DENABLE_HWSERIAL4
        -O2
        -g2
        -ggdb2
        -fexceptions
        -Wall
        -Wextra

debug_build_flags =
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-D USBCON
        -D ENABLE_USB_SER
        -DENABLE_HWSERIAL4
        -O2
        -g2
        -ggdb2
        -fexceptions
        -Wall
        -Wextra
        -DSERIAL_DEBUG

[env:esp32c3_supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
upload_speed = 921600
monitor_port = /dev/ttyACM0
monitor_speed = 115200
monitor_filters = direct
lib_deps =
  h2zero/NimBLE-Arduino @ 1.4.2

build_src_filter = +<ESP32/*> -<Weact/*>
build_type = debug
check_skip_packages=true
build_flags = 
        -DARDUINO_USB_MODE=1
        -DARDUINO_USB_CDC_ON_BOOT=1
        -Wall
        -Wextra
        -Wunused-variable
        -Wunused-function

debug_build_flags =
        -DARDUINO_USB_MODE=1
        -DARDUINO_USB_CDC_ON_BOOT=1
        -Wall
        -Wextra
        -Wunused-variable
        -Wunused-function
        -DSERIAL_DEBUG

board_build.flash_mode = dio
board_build.mcu = esp32c3

[env:espwroom32]
platform = espressif32
board = upesy_wroom
framework = arduino

; change microcontroller
;board_build.mcu = esp32

; change MCU frequency
;board_build.f_cpu = 240000000L

lib_deps =
        h2zero/NimBLE-Arduino @ 2.3.9
        pablomarquez76/PS4_Controller_Host@^1.1.1

build_src_filter = +<ESP32/*> -<Weact/*>